"""empty message

Revision ID: a9356467c409
Revises: fcc2c80ba06a
Create Date: 2021-02-09 08:20:51.507714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9356467c409'
down_revision = 'fcc2c80ba06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_tokens', sa.Column('agent', sa.String(), nullable=True))
    op.add_column('active_tokens', sa.Column('platform', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_tokens', 'platform')
    op.drop_column('active_tokens', 'agent')
    # ### end Alembic commands ###
